blog/config/routes.rb
Blog::Application.routes.draw do
  resources :tests

  devise_for :users, :controllers => {:sessions => 'sessions'}

  root :to => 'pages#index'

end

blog/app/models/personal_blog.rb
class PersonalBlog < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :posts
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :name

  belongs_to :user
  belongs_to :personal_blog
end

blog/app/models/test.rb
class Test < ActiveRecord::Base
  # attr_accessible :title, :body
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

blog/app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def edit
    @blog = Test.find(current_user.blog)
  end

  def create
    @blog = Test.new(params[:test])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Test was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @blog = Test.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:test])
        format.html { redirect_to @blog, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog = Test.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end
end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => "sessions#failure")
    return sign_in_and_redirect(resource_name, resource)
  end
  
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    return render :json => {:success => true, :redirect => stored_location_for(scope) || after_sign_in_path_for(resource)}
  end

  def failure
    return render:json => {:success => false, :errors => ["Login failed."]}
  end
end

blog/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tests }
    end
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
    @test = Test.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test }
    end
  end

  # GET /tests/new
  # GET /tests/new.json
  def new
    @test = Test.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test }
    end
  end

  # GET /tests/1/edit
  def edit
    @test = Test.find(params[:id])
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(params[:test])

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render json: @test, status: :created, location: @test }
      else
        format.html { render action: "new" }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tests/1
  # PUT /tests/1.json
  def update
    @test = Test.find(params[:id])

    respond_to do |format|
      if @test.update_attributes(params[:test])
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test = Test.find(params[:id])
    @test.destroy

    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/pages_helper.rb
module PagesHelper
end

blog/app/helpers/tests_helper.rb
module TestsHelper
end

blog/app/views/layouts/_sign_in.html.erb
<%= form_for("user", :html => { :id => 'user-login-form' }, :url => user_session_path, :remote => true) do |f| %>
  <div class="alert alert-error hide" data-dismiss="alert"></div>

  <%= f.text_field :email, :class => "span3", :placeholder => "Username" %>
  <%= f.password_field :password, :class => "span3", :placeholder => "Password" %>
  <label class="checkbox">
    <%= f.check_box :remember_me %> Remember Me
  </label>
  <%= f.submit 'Sign in', :class => "btn btn-info btn-block" %>
  <%= link_to "Forgot your password?", new_password_path('user') %>
<% end %> 

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Blog</a>
          <ul class="nav pull-right">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          </ul>
          <ul class="nav pull-right" role="navigation">
            <li class="dropdown">
              <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Sign in <b class="caret"></b></a>
              <ul class="dropdown-menu well" role="menu" aria-labelledby="drop1">
                <%= render "layouts/sign_in", :partial => true %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">

            <%= yield %>

            </div>

            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>

                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Blog 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

blog/app/views/pages/index.html.erb
Hello

blog/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>